// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMcy4WhyNqB35kHwoDXofbTrRlZ9w4H1U',
    appId: '1:616582614156:web:ae4b067964b4b0be33ffa9',
    messagingSenderId: '616582614156',
    projectId: 'todo-list-e4e28',
    authDomain: 'todo-list-e4e28.firebaseapp.com',
    storageBucket: 'todo-list-e4e28.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOzySgaeWfEs-miBPUDRO82pyU_EvlB2o',
    appId: '1:616582614156:android:312860bced2f89bf33ffa9',
    messagingSenderId: '616582614156',
    projectId: 'todo-list-e4e28',
    storageBucket: 'todo-list-e4e28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT8hDEInFdHCRCIHxJGFTMlUCXmCz9v1c',
    appId: '1:616582614156:ios:0c7ba49025bd9c5933ffa9',
    messagingSenderId: '616582614156',
    projectId: 'todo-list-e4e28',
    storageBucket: 'todo-list-e4e28.appspot.com',
    iosClientId: '616582614156-bkdokelofo3m5ea1hkb27u6gqfq1id12.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoList',
  );
}
